### ISSUE TITLE
ISSUE-19766 - Slack notification app-sync-succeeded fails when using sources in Application

### ISSUE THREAD

**Issue by eogns47** [Argo-OSS/argo-cd#10]
원본 이슈: https://buly.kr/2fcC4kj
작업 브랜치: issue-19766

**Comment by daengdaengLee** [comment]
* 슬랙 메시지 템플릿 위치 : `notifications_catalog/templates`
* 위 폴더의 템플릿 파일들에서 `.app.spec.source.repoURL` 를 바로 참조하는 곳에서 멀티 소스 등록되어 있는지 분기하여 처리
* Makefile 에서 카탈로그 재생성하여 `notifications_catalog/install.yaml` 생성
