### ISSUE TITLE
ISSUE-19071 - hydrator: add unit tests for new git client functions

### ISSUE THREAD

**Issue by daengdaengLee** [Argo-OSS/argo-cd#4]
[ISSUE-19071 - hydrator: add unit tests for new git client functions](https://tinyurl.com/yn9tfmy2)

## 이슈 내용
* 새로 추가한 메소드(코드)에 대해 유닛 테스트 작성하기

## 연관 이슈/PR
- [x] [SetAuthor 메소드에 대해 테스트 작성](https://tinyurl.com/ynedryat)
- [x] [CheckoutOrOrphan 메소드에 대해 테스트 작성](https://tinyurl.com/mv6vm98v)
- [x] [CheckoutOrNew 메소드에 대해 테스트 작성](https://tinyurl.com/4hm3trvj)
- [x] [RemoveContents 메소드에 대해 테스트 작성](https://tinyurl.com/yeyn328c)
- [x] [CommitAndPush 메소드에 대해 테스트 작성](https://tinyurl.com/2ze9mwk2)

## 구현 목록
- [x] SetAuthor UnitTest
- [x] CheckoutOrOrphan UnitTest
- [x] CheckoutOrNew UnitTest
- [x] RemoveContents UnitTest
- [x] CommitAndPush UnitTest

## 학습 내용

**Comment by Jack-R-lantern** [comment]
매우 좋습니다 ㅋㅋㅋ 벌써 PR이 2개나 merge 됐군요.

**Comment by leehosu** [comment]
오 댑악..
