### ISSUE TITLE
ISSUE-19070 - hydrator: handle sourceHydrator fields from webhook

### ISSUE THREAD

**Issue by daengdaengLee** [Argo-OSS/argo-cd#8]
[ISSUE-19070 - hydrator: handle sourceHydrator fields from webhook](https://tinyurl.com/exw2f7az)

## 이슈 내용

* WebHook 으로 이벤트를 받았을 때 hydrate 대상인지 체크하여 대상인 경우 hydrate 로직 실행

## 연관 이슈/PR

* https://tinyurl.com/2yvr2vhj

## 구현 목록

* PR 내용 참고 

## 학습 내용

**Comment by daengdaengLee** [comment]
@Jack-R-lantern 님, 혹시 이 이슈 관련해서 위와 같은 전략으로 접근해도 괜찮을까요? 

첫 PR로 `webhook 에서 hydrate 필요한 시점 탐지 -> 기존 refresh 실행 -> refresh 중 hydrate 재실행` 까지만 하고,
후속 PR 로 어노테이션 추가, 별도 processor 로직 개발을 진행하는 형태로요.

Draft 로 PR 열면서 메인테이너에서 의견을 물어보려고 합니다. 메인테이너가 이런 접근을 받아주기도 하나요?

**Comment by Jack-R-lantern** [comment]
@daengdaengLee
ArgoCD 분위기가 어떨진 모르겠지만
Draft PR을 열고 구현 목표를 체크 박스로 정리해서
구현 목표를 달성하고 comment에서 메인테이너 의견을 물어보는게 좋아보여요.

아니면 발행된 이슈에서 구현목표를 두개로 생각한다고 먼저 언급하고 PR을 두번 제출하겠다고 언급해도 좋을것 같습니다
