### ISSUE TITLE
ISSUE-19269 - Commas and dollar signs improperly passed to Helm

### ISSUE THREAD

**Issue by daengdaengLee** [Argo-OSS/argo-cd#9]
원본 이슈 : https://tinyurl.com/2x44ec66
작업 브랜치 : issue-19269

## 개요

* 1720번 PR : 최초 cleanHelmParameters 함수 도입
* 1732번 PR : cleanHelmParameters 함수 호출 위치 수정
* 1865번 PR : cleanHelmParameters 함수 호출하는 helmCmdExt 함수 삭제, cleanHelmParameters 함수 호출하는 곳 없어짐
* 2334번 PR : cleanHelmParameters 함수 helm.Template 함수에서 호출하도록 수정
* 2377번 PR : 
    * helm.Template 함수 코드 중 일부를 helmTemplate (repository.go) 함수로 옮기는 과정에서 cleanHelmParameters 함수 호출 부분 누락됨
    * `cleanHelmParameters` 함수 삭제됨
    * `util/helm/cmd.go` 에 `cleanHelmParameters` 함수의 단위 동작을 하는 `cleanSetParameters` 함수 추가됨
    * `util/helm/cmd.go` 의 `Cmd.template` 함수에서 `cleanSetParameters` 호출해서 처리중
    * `opts.Parameters` -> `templateOpts.SetString`, `templateOpts.Set` 으로 매핑됨
    * 왜 정상 동작 안 할까? : `cleanSetParameters` 함수가 기존 이슈의 문제를 해결할 수 있는지 확인해봐야 함. 
* 2415번 PR : `templateOpts.SetString`, `templateOpts.Set` 값에 `env.Envsubst` 적용 추가됨. 이것 때문에 정상 동작 안 하나?
* `,` 문제랑 `$` 문제랑 분리해서 해결해야 할 듯. 위 `env.Envsubst` 쪽에서 환경변수 보정해줄 때 `$` 사용하기 때문에 이건 별도 문제로 봐야 할 듯
* `templateOpts.SetString` 은 `forceString` 을 `true` 로 지정한 파라미터 값이므로 `env.Envsubst` 처리를 빼야 하나?

## 파트 1 (`$` 문제)

* `reposerver/repository/repository.go` 파일의 `helmTemplate` 함수에서 `templateOpts.SetString` 에 대해서는 `env.Envsubst` 처리 빼기
* PR : https://tinyurl.com/4kmhs57t

## 파트 2 (`,` 문제)

* `util/helm/cmd.go` 파일의 `cleanSetParameters` 함수에서 정규표현식 치환 로직 수정 필요
* 정규표현식에 놓치는 경우들이 있음
  * 예시1 : 맨 앞에 `,` 문자가 오는 경우
  * 예시2 : 연속해서 `,` 문자가 오는 경우 두 번째 문자 (`,,` 에서 두 번쨰)

**Comment by daengdaengLee** [comment]
한 Git 커밋에 여러 기여자 작성하는 방법입니다.
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

파트 2 부분 커밋을 쪼개기 어려우면 위 방법으로 두 분이 같이 작업하시면 좋을 것 같아요.

**Comment by eogns47** [comment]
> 한 Git 커밋에 여러 기여자 작성하는 방법입니다. https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
> 
> 파트 2 부분 커밋을 쪼개기 어려우면 위 방법으로 두 분이 같이 작업하시면 좋을 것 같아요.

감사합니다!!
